openapi: 3.0.0
info:
  version: "3.0.0"
  title: GovPay - API Ragioneria
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: ${it.govpay.apiurl}/govpay/backend/api/ragioneria/rs/basic/v3/
tags:
  - name: Rendicontazioni
  - name: Riscossioni
  - name: Riconciliazioni
  - name: Utenti
    description: Anagrafica degli Utenti
security:
  - basicAuth: []    
paths:
  '/riconciliazioni':
    get:
      summary: Elenco dei movimenti di cassa riconciliati
      operationId: findRiconciliazioni
      tags:
        - Riconciliazioni
      parameters:
        - $ref: '#/components/parameters/pagina'
        - $ref: '#/components/parameters/risultatiPerPagina'
        - $ref: '#/components/parameters/idDominio'
        - $ref: '#/components/parameters/dataDa'
        - $ref: '#/components/parameters/dataA'
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
        - $ref: '#/components/parameters/sct'
      responses:
        '200':
          description: Dettaglio dell'incasso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riconciliazioni'
              example:
                numRisultati: 2
                numPagine: 1
                risultatiPerPagina: 25
                pagina: 1
                risultati:
                  - id: '12345'
                    idDominio: 01234567890
                    importo: 10
                    data: '2020-12-31'
                    dataValuta: '2020-12-31'
                    dataContabile: '2020-12-31'
                    contoAccredito: IT60X0542811101000000123456
                    sct: 2017-01-01ABI00000011234
                    trn: 2017-01-01ABI00000011234
                    iuv: RF23567483937849450550875
                  - id: '12346'
                    idDominio: 01234567890
                    importo: 100.01
                    data: '2020-12-31'
                    dataValuta: '2020-12-31'
                    dataContabile: '2020-12-31'
                    contoAccredito: IT60X0542811101000000123456
                    idFlussoRendicontazione: '2020-11-21GovPAYPsp-1234567890'
                    causale: '000000000000000,00000000000000101,01EUR000000000000000,000000000000000000000000,000000000000,00/ZZ2SATISPAY EUROPE SA/ZZ3Comune Dimostrativo/PUR/LGPE-RIVERSAMENTO/URI/2020-11-21GovPAYPsp-1234567890/ZZ4/4184/ZZ4/ID1357a8662b2256347456532f53f9a9825357a8662b2b911eb8da402f53f9a9825'
                
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'        
  '/riconciliazioni/{idDominio}/{id}':
    parameters:
      - in: path
        name: idDominio
        description: Identificativo del creditore
        required: true
        schema:
          type: string  
          pattern: '(^([0-9]){11}$)'
      - in: path
        name: id
        description: Identificativo dell'operazione di riconciliazione
        required: true
        schema:
          type: string  
    put:
      summary: Riconciliazione di un movimento di cassa
      operationId: addRiconciliazione
      tags:
        - Riconciliazioni
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiconciliazionePost'
            example:
              importo: 100.01
              dataValuta: '2020-12-31'
              dataContabile: '2020-12-31'
              contoAccredito: IT60X0542811101000000123456
              sct: 00000011234
              causale: '000000000000000,00000000000000101,01EUR000000000000000,000000000000000000000000,000000000000,00/ZZ2SATISPAY EUROPE SA/ZZ3Comune Dimostrativo/PUR/LGPE-RIVERSAMENTO/URI/2020-11-21GovPAYPsp-1234567890/ZZ4/4184/ZZ4/ID1357a8662b2256347456532f53f9a9825357a8662b2b911eb8da402f53f9a9825'
      responses:
        '201':
          $ref: '#/components/responses/Riconciliazione'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'          
    get:
      summary: Dettaglio di un movimento di cassa riconciliato
      operationId: getRiconciliazione
      tags:
        - Riconciliazioni
      responses:
        '200':
          description: Dettaglio dell'incasso
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Riconciliazione'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'        
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      operationId: getProfilo
      responses:
        '200':
          description: Autorizzazioni dell'utenza chiamante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profilo'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'      
components:
  schemas:
    Contabilita:
      type: object
      properties:
        quote:
          type: array
          items: 
            $ref: '#/components/schemas/QuotaContabilita'
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità  
    Pendenza:
      type: object
      description: Dati della pendenza
      required:
        - idA2A
        - idPendenza
        - dataCaricamento
      properties:
        idA2A:
          type: string
          description: Identificativo del gestionale responsabile della pendenza
          example: A2A-12345
        idPendenza:
          type: string
          description: Identificativo della pendenza nel gestionale responsabile
          example: abcdef12345
        idDominio:
          type: string
          description: Identificativo del dominio creditore
          example: 1234567890
        idUnitaOperativa:
          type: string
          description: Identificativo dell'unita' operativa
          example: UO33132
        idTipoPendenza:
          type: string
          description: Identificativo della tipologia pendenza
          example: IMU
        causale:
          type: string
          description: Descrizione da inserire nell'avviso di pagamento
          example: 'Sanzione CdS n. abc00000'
          maxLength: 140     
        dataScadenza:
          type: string
          format: date
          description: Data di scadenza della pendenza, decorsa la quale non è più pagabile.
          example: '2020-12-31'
        annoRiferimento:
          type: number
          description: Anno di riferimento della pendenza
          example: 2020
        cartellaPagamento:
          type: string
          description: Identificativo della cartella di pagamento a cui afferisce la pendenza
          example: ABC00000001
        datiAllegati:
          type: object
          description: Dati applicativi allegati dal gestionale secondo un formato proprietario.
        tassonomia:
          type: string
          description: Macro categoria della pendenza secondo la classificazione del creditore
          example: Sanzioni
        direzione:
          type: string
          description: Identificativo della direzione interna all'ente creditore
          example: Direzione ABC
        divisione:
          type: string
          description: Identificativo della divisione interna all'ente creditore
          example: Divisione001
        UUID:
          type: string
          description: Parametro di randomizzazione delle URL di pagamento statiche            
    QuotaContabilita:
      type: object
      required:
        - capitolo
        - annoEsercizio
        - importo
      properties:
        capitolo:
          type: string
          description: Codice del capitolo
          maxLength: 64
          example: '0101'
        annoEsercizio:
          type: number
          description: Anno di esercizio
          example: 2020
        importo:
          type: number
          description: Importo della voce di contabilita'
          example: 10.01
        accertamento:
          type: string
          description: Codice dell’accertamento
          maxLength: 64      
          example: '22'
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità  
      example: 
        capitolo: '1234'
        annoEsercizio: 2020
        importo: 123.50
        accertamento: '1234'
        proprietaCustom: 
          capo: 1
          riferimento: abc123
    Riconciliazione:
      type: object
      allOf:
        - $ref: '#/components/schemas/RiconciliazioneIndex' 
        - type: object
          properties: 
            riscossioni:
              type: array
              items: 
                $ref: '#/components/schemas/RiscossioneIndex' 
    RiconciliazioneIndex:
      type: object
      allOf:
        - type: object
          required:
            - id
            - idDominio
            - importo
            - data
          properties:
            id:
              type: string
              description: Identificativo della riconciliazione assegnato da GovPay
              example: '12345' 
            idDominio:
              type: string
              description: Identificativo ente creditore
              example: 01234567890
            importo:
              type: number
              example: 100.01
              description: Importo del riversamento. Se valorizzato, viene verificato che corrisponda a quello dei pagamenti riconciliati.
            data:
              type: string
              format: date-time
              description: Data di esecuzione della riconciliazione
              example: '2020-12-31'              
            dataValuta:
              type: string
              format: date
              description: Data di valuta dell'incasso
              example: '2020-12-31'
            dataContabile:
              type: string
              format: date
              description: Data di contabile dell'incasso
              example: '2020-12-31'
            contoAccredito:
              type: string
              description: Identificativo del conto di tesoreria su cui sono stati incassati i fondi
              example: IT60X0542811101000000123456
            sct:
              type: string
              description: Identificativo Sepa Credit Transfer
              example: 2017-01-01ABI00000011234
            trn:
              type: string
              description: Transaction reference number. Se valorizzato viene verificato che corrisponda a quello indicato nel Flusso di Rendicontazione.
              example: 2017-01-01ABI00000011234
            causale:
              type: string
              description: Causale bancaria dell'SCT di riversamento fondi dal PSP al conto di accredito.
        - oneOf:
          - description: Identificativo univoco di versamento.
            type: object
            required:
              - iuv
            properties:
              iuv:
                type: string
                example: RF23567483937849450550875
          - description: Identificativo del flusso di rendicontazione.
            type: object
            required:
              - idFlussoRendicontazione
            properties:
              idFlussoRendicontazione:
                type: string
                example: 2020-11-21GovPAYPsp-1234567890
    RiconciliazionePost:
      allOf:
        - type: object
          properties:
            importo:
              type: number
              example: 100.01
              description: Importo del riversamento. Se valorizzato, viene verificato che corrisponda a quello dei pagamenti riconciliati.
            dataValuta:
              type: string
              format: date
              description: Data di valuta dell'incasso
              example: '2020-12-31'
            dataContabile:
              type: string
              format: date
              description: Data di contabile dell'incasso
              example: '2020-12-31'
            contoAccredito:
              type: string
              description: Identificativo del conto di tesoreria su cui sono stati incassati i fondi
              example: IT60X0542811101000000123456
            sct:
              type: string
              description: Identificativo Sepa Credit Transfer
              example: 2017-01-01ABI00000011234
        - oneOf:
          - description: Causale dell'operazione di riversamento dal PSP alla Banca Tesoriera.
            type: object
            required:
              - causale
            properties:
              causale:
                type: string
                example: /PUR/LGPE-RIVERSAMENTO/URI/2017-01-01ABI00000011234
          - description: Identificativo univoco di versamento.
            type: object
            required:
              - iuv
            properties:
              iuv:
                type: string
                example: RF23567483937849450550875
          - description: Identificativo del flusso di rendicontazione.
            type: object
            required:
              - idFlussoRendicontazione
            properties:
              idFlussoRendicontazione:
                type: string
                example: 2017-11-21GovPAYPsp1-10:27:27.903                  
    Riconciliazioni:
      type: object
      allOf:
        - $ref: '#/components/schemas/Lista' 
        - type: object
          properties:
            risultati:
              type: array
              items: 
                $ref: '#/components/schemas/RiconciliazioneIndex'         
    RiscossioneIndex:
      type: object
      required:
        - dominio
        - iuv
        - iur
        - indice
        - tipo
        - importo
        - data
      properties:
        iuv:
          type: string
          description: Identificativo univoco di versamento
          example: RF23567483937849450550875
        iur:
          type: string
          description: Identificativo univoco di riscossione.
          example: '1234acdc'
        indice:
          type: number
          description: indice posizionale della voce pendenza riscossa
          example: 1
        tipo:
          $ref: '#/components/schemas/TipoRiscossione'
        importo:
          type: number
          description: Importo riscosso. 
          example: 10.01
        data:
          type: string
          format: date
          description: Data di esecuzione della riscossione
          example: '2020-12-31'
        vocePendenza:
          $ref: '#/components/schemas/VocePendenza'       
    VocePendenza:
      type: object
      required:
        - idVocePendenza
        - pendenza
      properties:
        idDominio:
          type: string
          description: Identificativo del dominio creditore
          example: 1234567890      
        idVocePendenza:
          type: string
          description: Identificativo della voce di pedenza nel gestionale proprietario
          example: abcdef12345_1   
        descrizione:
          type: string
          description: descrizione della voce di pagamento
          example: Sanzione CdS n. abc00000
          minLength: 1
          maxLength: 140  
        datiAllegati:
          type: object
          description: Dati applicativi allegati dal gestionale secondo un formato proprietario.  
        descrizioneCausaleRPT:
          type: string
          description: Testo libero per la causale versamento
          example: Sanzione CdS n. abc00000
          minLength: 1
          maxLength: 140
        contabilita:
          $ref: '#/components/schemas/Contabilita'
        pendenza:
          $ref: '#/components/schemas/Pendenza'  

    Acl:
      type: object
      required:
        - servizio
        - autorizzazioni
      properties:
        ruolo:
          type: string
          description: ruolo a cui si applica l'acl
          example: Operatore
        principal:
          type: string
          description: principal a cui si applica l'acl
          example: user001
        servizio:
          $ref: "#/components/schemas/TipoServizio"
        autorizzazioni:
          $ref: "#/components/schemas/TipoAutorizzazione"  
    Dominio:
      type: object
      required:
        - idDominio
        - ragioneSociale
      properties:
        idDominio:
          type: string
          description: Codice fiscale
          example: 01234567890
          minLength: 1
          maxLength: 35          
        ragioneSociale:
          type: string
          description: Ragione sociale
          example: Ufficio due
          minLength: 1
          maxLength: 70
    FaultBean:
      type: object
      required:
        - categoria
        - codice
        - descrizione
      properties:
        categoria:
          type: string
          description: >-
            Categoria dell'errore riscontrato:
             * `AUTORIZZAZIONE` - Operazione non autorizzata
             * `RICHIESTA` - Richiesta non valida
             * `OPERAZIONE` - Operazione non eseguibile
             * `PAGOPA` - Errore da PagoPA
             * `EC` - Errore da Ente Creditore
             * `INTERNO` - Errore interno
          enum:
            - AUTORIZZAZIONE
            - RICHIESTA
            - OPERAZIONE
            - PAGOPA
            - EC
            - INTERNO
        codice:
          type: string
          description: Codice di errore
        descrizione:
          type: string
          description: Descrizione dell'errore
        dettaglio:
          type: string
          description: Descrizione aggiuntiva         
    Lista:
      type: object
      properties:
        numRisultati:
          type: number
          format: integer
          example: '100'
        numPagine:
          type: number
          format: integer
          example: '4'
        risultatiPerPagina:
          type: number
          format: integer
          example: '25'
        pagina:
          type: number
          format: integer
          example: '1'
        prossimiRisultati:
          type: string
          format: integer
          example: '/risorsa?pagina=2' 
    Pagina:
      type: integer
      default: 1
    Profilo:
      type: object
      required: 
        - nome
        - domini
        - tipiPendenza
        - acl
      properties:
        nome:
          type: string
          description: Nome o principal dell'utenza
        domini:
          type: array
          description: domini su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/Dominio'
        tipiPendenza:
          type: array
          description: tipologie di pendenza su cui e' abilitato ad operare
          items:
            $ref: '#/components/schemas/TipoPendenza'
        acl:
          type: array
          items:
            $ref: '#/components/schemas/Acl'
        anagrafica:
          $ref: '#/components/schemas/Soggetto'
        identityData:
          type: object 
    Soggetto:
      description: dati anagrafici di un versante o pagatore.
      type: object
      required:
        - tipo
        - identificativo
      properties:
        tipo:
          $ref: "#/components/schemas/TipoSoggetto"
        identificativo:
          description: codice fiscale o partita iva del soggetto
          type: string
          example: RSSMRA30A01H501I
          minLength: 1
          maxLength: 35
        anagrafica:
          description: nome e cognome o altra ragione sociale del soggetto
          type: string
          example: Mario Rossi
          minLength: 1
          maxLength: 70
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: 00000
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          example: mario.rossi@host.eu
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"
        cellulare:
          type: string
          example: +39 000 1234567    
          pattern: "\\+[0-9]{2,2}\\s[0-9]{3,3}\\-[0-9]{7,7}" 
    TipoAutorizzazione:
      type: array
      items:
        type: string
        enum:
         - Lettura
         - Scrittura
      example:
        - Lettura
        - Scrittura 
    TipoPendenza:
      type: object
      required:
        - idTipoPendenza
        - descrizione
      properties:
        idTipoPendenza:
          type: string
          example: REFNIDO
        descrizione:
          type: string
          example: Refezione scolastica Asilo Nido         
    TipoRiscossione:
      description: > 
        Tipologia della voce riscossa
         * ENTRATA: Entrata in tesoreria
         * MBT: Marca da bollo telematica
         * ALTRO_INTERMEDIARIO: Entrata relativa a un intermediario esterno
      type: string
      enum:
        - ENTRATA
        - MBT
        - ALTRO_INTERMEDIARIO
    TipoServizio:
      type: string
      enum:
        - Anagrafica PagoPA
        - Anagrafica Creditore
        - Anagrafica Applicazioni
        - Anagrafica Ruoli
        - Pagamenti
        - Pendenze
        - Rendicontazioni e Incassi
        - Giornale degli Eventi
        - Configurazione e manutenzione
      example:
        Pendenze e Pagamenti             
    TipoSoggetto:
      description: >-
        tipologia di soggetto, se persona fisica (F) o giuridica
        (G)
      type: string
      enum:
        - G
        - F
      example: F
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    idDominio:
      name: idDominio
      in: query
      description: Identificativo del dominio dell'ente
      required: false
      schema:
        type: string
        pattern: '(^([0-9]){11}$)'
    idFlussoCaseInsensitive:
      in: query
      name: idFlussoCaseInsensitive
      description: Indica se effettuare la ricerca per Identificativo flusso in modalita' case insensitive
      required: false
      schema:
        type: boolean
    iuv:
      name: iuv
      in: query
      description: Identificativo del versamento
      required: false
      schema:
        type: string
    ccp:
      name: ccp
      in: query
      description: Codice contesto pagamento
      required: false
      schema:
        type: string
    dataDa:
      name: dataDa
      in: query
      description: Inizio della finestra temporale di osservazione
      required: false
      schema:
        type: string  
        format: date-time     
    dataA:
      name: dataA
      in: query
      description: Fine della finestra temporale di osservazione
      required: false
      schema:
        type: string  
        format: date-time     
    direzione:
      name: direzione
      in: query
      description: Identificativo della direzione interna all'ente creditore
      required: false
      schema:
        type: string
        example: Direzione ABC
    divisione:
      name: divisione
      in: query
      description: Identificativo della divisione interna all'ente creditore
      required: false
      schema:
        type: string
        example: Divisione001               
    campi:
      name: campi
      in: query
      description: Fields to retrieve
      required: false
      schema:
        type: string
    idA2A:
      name: idA2A
      in: query
      description: Identificativo del gestionale ente
      required: false
      schema:
        type: string
    idPendenza:
      name: idPendenza
      in: query
      description: Identificativo della pendenza nel gestionale ente
      required: false
      schema:
        type: string
    idPagamento:
      name: idPagamento
      in: query
      description: Identificativo della richiesta di pagamento
      required: false
      schema:
        type: string
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'  
    maxRisultati:
      name: maxRisultati
      in: query
      description: >-
            Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati
      required: false
      schema:
        type: boolean
        default: true
      example: true
    metadatiPaginazione:
      name: metadatiPaginazione
      in: query
      description: >- 
              Indica se il servizio calcola e valorizza i dati di paginazione o meno
      required: false
      schema:
        type: boolean
        default: true
      example: true
    ordinamento:
      name: ordinamento
      in: query
      description: Sorting order
      required: false
      schema:
        type: string
    pagina:
      name: pagina
      in: query
      description: Numero di pagina di risultato
      required: false
      schema:
        $ref: '#/components/schemas/Pagina'        
    risultatiPerPagina:
      name: risultatiPerPagina
      in: query
      description: How many items to return at one time (max 100)
      required: false
      schema:
        type: integer
        default: 25
        maximum: 200
    tipiRiscossione:
      in: query
      name: tipo
      description: Tipologia della riscossione (default [ENTRATA, MBT] )
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/TipoRiscossione'
    tipoRiscossione:
      name: tipoRiscossione
      in: query
      description: Tipo di riscossione
      required: false
      schema:
        $ref: '#/components/schemas/TipoRiscossione'
    sct:
      name: sct
      in: query
      description: Identificativo del Sepa Credit Transfert di riversamento da PSP a conto di accredito
      required: false
      schema:
        type: string
  headers:
    # Headers conform to http://zalando.github.io/restful-api-guidelines/index.html#132
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: integer
        format: int32
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        type: integer
        format: int32
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        type: integer
        format: int32
    Retry-After:
      description: Retry contacting the endpoint *at least* after seconds. See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        type: integer
        format: int32
  responses:
    '400BadRequest':
      description: Richiesta non correttamente formata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: RICHIESTA
            codice: 00001
            descrizione: Messaggio di richiesta non valido
            dettaglio: Codice Avviso non conforme alle specifiche pagoPA
    '401NotAuthenticated':
      description: Richiesta non autenticata
    '403NotAuthorized':
      description: Richiesta non autorizzata
    '404NotFound':
      description: Risorsa inesistente
    '500ServiceUnavailable':
      description: Servizio non disponibile
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: INTERNO
            codice: INTERNO
            descrizione: Servizio non disponibile    
    'Riconciliazione':
      description: Riconciliazione
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Riconciliazione'
          example:
            id: '12345'
            idDominio: '01234567890'
            importo: 130.05
            dataValuta: '2020-12-31'
            dataContabile: '2020-12-31'
            contoAccredito: 'IT60X0542811101000000123456'
            sct: '00000011234'
            trn: 'SEPA-00000011234'
            idFlussoRendicontazione: '2020-11-21GovPAYPsp-1234567890'
            causale: '000000000000000,00000000000000101,01EUR000000000000000,000000000000000000000000,000000000000,00/ZZ2SATISPAY EUROPE SA/ZZ3Comune Dimostrativo/PUR/LGPE-RIVERSAMENTO/URI/2020-11-21GovPAYPsp-1234567890/ZZ4/4184/ZZ4/ID1357a8662b2256347456532f53f9a9825357a8662b2b911eb8da402f53f9a9825'
            riscossioni:
            - iuv: 'RF23567483937849450550875'
              iur: '1234acdc'
              indice: 1
              tipo: 'ENTRATA'
              importo: 100.01
              data: '2020-12-31'
              vocePendenza:
                idVocePendenza: 'abcdef12345_1'
                descrizione: 'Violazione del codice della strada n. abc00000'
                datiAllegati: 
                  targa: 'AB123CD'
                  indirizzo: 'Via Roma 12'
                  data: '2020-10-01'
                descrizioneCausaleRPT: "abc00000 31.12.2021 10.01"
                contabilita:
                  quote:
                  - capitolo: '1234'
                    annoEsercizio: 2020
                    importo: 90
                    accertamento: '1234'
                    proprietaCustom:
                      riferimento: 'abc123'
                  - capitolo: '1234'
                    annoEsercizio: 2020
                    importo: 10.01
                    accertamento: '5678'
                  proprietaCustom: 
                    descrizioneCapitolo: 'Lorem Ipsum'
                    capo: 1
                pendenza:
                  idA2A: 'A2A-12345'
                  idPendenza: 'abcdef12345'
                  idUnitaOperativa: 'UO33132'
                  tipoPendenza: 
                    idTipoPendenza: 'CDS'
                    descrizione: 'Violazioni del codice della strada'
                  causale: 'Sanzione CdS n. abc00000'
                  dataScadenza: '2020-12-31'
            - iuv: '301000001234567890'
              iur: 'A43def48ED'
              indice: 1
              tipo: 'ALTRO_INTERMEDIARIO'
              importo: 30.40
              data: '2020-12-31'
          
          
          
      
